import { countTokens } from './tokenCounter.js'

// ─── Helpers ────────────────────────────────────────────────────────────────

// FIX: sum all page tokens instead of using only first-page count
function getTotalTokens(info) {
  if (info.pages && info.pages.length > 0) {
    return info.pages.reduce((sum, p) => sum + (p.tokenCount || 0), 0)
  }
  return info.tokenCount || 0
}

// Detect site type from pages/headings to avoid generic boilerplate
function detectSiteType(info) {
  const allText = [
    info.description,
    ...(info.pages || []).map(p => `${p.title} ${p.description}`)
  ].join(' ').toLowerCase()

  if (allText.match(/repair|service|battery|screen|fix/)) return 'service'
  if (allText.match(/shop|buy|sell|price|mobile|phone|product/)) return 'ecommerce'
  if (allText.match(/api|sdk|endpoint|integration|developer/)) return 'developer-docs'
  if (allText.match(/install|npm|yarn|cli|package/)) return 'technical'
  if (allText.match(/blog|article|post|news/)) return 'content'
  return 'business'
}

// Extract what an AI agent can actually DO with this site
function extractCapabilities(info) {
  const caps = []
  const pages = info.pages || []

  pages.forEach(p => {
    const t = (p.title + ' ' + (p.description || '')).toLowerCase()
    if (t.match(/service|repair/)) caps.push(`Find available services at ${p.url}`)
    if (t.match(/about|contact/)) caps.push(`Learn about the business at ${p.url}`)
    if (t.match(/shop|product|mobile|phone/)) caps.push(`Browse products at ${p.url}`)
    if (t.match(/blog|article/)) caps.push(`Read content at ${p.url}`)
  })

  return caps.length > 0 ? caps : ['Browse the site content']
}

// Build page description — use meta description if available, else derive from title
function pageDesc(p) {
  if (p.description && p.description !== 'No description') return p.description
  // derive a readable fallback from the title
  const title = p.title || p.url
  return `${title} page of the site`
}


// ─── 1. llms.txt ─────────────────────────────────────────────────────────────
// Standard: https://llmstxt.org
// Purpose: help AI agents discover what pages exist and how large they are

export function generateLLMSTxt(info) {
  const totalTokens = getTotalTokens(info)

  const pagesList = info.pages && info.pages.length > 0
    ? info.pages.map(p =>
        `- [${p.title || p.url}](${p.url}): ${pageDesc(p)} (~${p.tokenCount || 0} tokens)`
      ).join('\n')
    : info.headings.map(h =>
        `- [${h}](#${h.toLowerCase().replace(/\s+/g, '-')}): ${h} section`
      ).join('\n') || '- No pages detected'

  // FIX: compute real total token budget across all pages
  const budgetNote = totalTokens < 10000
    ? 'Entire site fits in a single AI context window.'
    : totalTokens < 50000
    ? 'Site is medium-sized. Consider reading page-by-page.'
    : 'Site is large. Use the page index above to read only relevant sections.'

  return `# ${info.name}

> ${info.description}

## Pages
${pagesList}

## Token Budget
- Total tokens across all pages: ~${totalTokens}
- Total pages: ${info.pages ? info.pages.length : 1}
- Total words: ${info.wordCount}
- ${budgetNote}

## Notes
- Code examples found: ${info.codeBlocks}
- Generated by AEO Studio
`
}


// ─── 2. AGENTS.md ────────────────────────────────────────────────────────────
// Purpose: tell AI coding agents / assistants what this project IS
// and how to navigate it — NOT generic npm instructions

export function generateAgentsMd(info) {
  const totalTokens = getTotalTokens(info)
  const siteType = detectSiteType(info)
  const capabilities = extractCapabilities(info)

  // Only show dev instructions if it's actually a technical/dev project
  const devSection = (siteType === 'technical' || siteType === 'developer-docs')
    ? `\n## How to Run Locally\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
    : ''

  // Build page-by-page navigation guide
  const navGuide = info.pages && info.pages.length > 0
    ? info.pages.map(p =>
        `- **${p.title || p.url}** → ${p.url}\n  ${pageDesc(p)}`
      ).join('\n')
    : info.headings.map(h => `- ${h}`).join('\n') || '- See site directly'

  return `# AGENTS.md

## Project Overview
**Name:** ${info.name}
**Type:** ${siteType} site
**Description:** ${info.description}

## What an AI Agent Can Do Here
${capabilities.map(c => `- ${c}`).join('\n')}

## Page Navigation Guide
${navGuide}

## Content Stats
| Metric | Value |
|--------|-------|
| Total pages | ${info.pages ? info.pages.length : 1} |
| Total words | ${info.wordCount} |
| Total tokens | ~${totalTokens} |
| Code blocks | ${info.codeBlocks} |
${devSection}
## Reading Strategy for AI Agents
${totalTokens < 10000
  ? '- This site is small. You can read all pages in one context window.'
  : '- Read llms.txt first to pick relevant pages. Do not load all pages at once.'
}
- Start with the page most relevant to the user query
- Use page descriptions in llms.txt to decide what to fetch

## Important
- Do not assume content not listed above exists
- Verify pricing, availability, and contact info directly from the site
`
}


// ─── 3. skill.md ─────────────────────────────────────────────────────────────
// Purpose: help AI agents decide WHEN and HOW to use this site as a tool/source
// Follows the pattern used by Claude, GPT plugins, and MCP skill definitions

export function generateSkillMd(info) {
  const totalTokens = getTotalTokens(info)
  const siteType = detectSiteType(info)
  const capabilities = extractCapabilities(info)

  // Generate trigger phrases based on actual content
  const triggers = buildTriggers(info, siteType)
  const nonTriggers = buildNonTriggers(siteType)

  // Key sections for quick lookup
  const keySections = info.pages && info.pages.length > 0
    ? info.pages.map(p =>
        `- **${p.title || p.url}** (${p.url}) — ${pageDesc(p)} | ~${p.tokenCount || 0} tokens`
      ).join('\n')
    : info.headings.map(h => `- ${h}`).join('\n') || '- See documentation'

  return `# skill.md — ${info.name}

## What This Source Does
${info.description}

**Site type:** ${siteType}

## When to Use This Source
Use this when the user asks about:
${triggers.map(t => `- ${t}`).join('\n')}

## When NOT to Use This Source
${nonTriggers.map(t => `- ${t}`).join('\n')}

## Capabilities
${capabilities.map(c => `- ${c}`).join('\n')}

## Key Pages (Quick Reference)
${keySections}

## Token Budget
| Resource | Tokens |
|----------|--------|
| Total (all pages) | ~${totalTokens} |
| Pages available | ${info.pages ? info.pages.length : 1} |
| Largest page | ~${getLargestPage(info)} tokens |
| Recommended read limit | ~25,000 tokens per call |

## How to Read This Site Efficiently
1. Check \`llms.txt\` to find the most relevant page
2. Fetch only that page — avoid loading all pages at once
3. If the answer needs multiple pages, fetch them sequentially
4. Stop fetching when the user's question is answered

## Limitations
- Token budget: ~${totalTokens} total; split across ${info.pages ? info.pages.length : 1} pages
- No code examples found on this site${info.codeBlocks > 0 ? ` — actually ${info.codeBlocks} found` : ''}
- Content may change — always verify live data (prices, availability, hours) by fetching the URL
`
}


// ─── 4. llms-full.txt (bonus) ─────────────────────────────────────────────────
// Purpose: single file with all content for agents with large context windows
// Follows emerging llmstxt.org standard for full-content variant

export function generateLLMSFullTxt(info) {
  const totalTokens = getTotalTokens(info)

  const fullContent = info.pages && info.pages.length > 0
    ? info.pages.map(p => `## ${p.title || p.url}
URL: ${p.url}
Tokens: ~${p.tokenCount || 0}

${p.description || pageDesc(p)}

${p.fullText ? p.fullText.slice(0, 3000) : '(Full text not captured — fetch the URL directly)'}

---`).join('\n\n')
    : '(No page content available — run a full crawl audit)'

  return `# ${info.name} — Full Content

> ${info.description}
> Total tokens: ~${totalTokens} | Pages: ${info.pages ? info.pages.length : 1}

---

${fullContent}
`
}


// ─── Internal helpers ─────────────────────────────────────────────────────────

function buildTriggers(info, siteType) {
  const name = info.name
  const base = {
    ecommerce: [
      `Buying or comparing products from ${name}`,
      `Asking about prices, availability, or models sold at ${name}`,
      `Looking for deals or offers at ${name}`,
    ],
    service: [
      `Asking about repair services offered by ${name}`,
      `Asking about service pricing, availability, or turnaround time`,
      `Questions about what ${name} can fix or service`,
    ],
    'developer-docs': [
      `How to integrate or use the ${name} API or SDK`,
      `Looking for code examples or endpoint references`,
      `Troubleshooting ${name} integration`,
    ],
    technical: [
      `How to install, configure, or use ${name}`,
      `Technical questions about ${name}`,
    ],
    content: [
      `Finding articles or guides published by ${name}`,
      `Researching topics covered on ${name}`,
    ],
    business: [
      `Learning about ${name} and what they offer`,
      `Contacting or finding information about ${name}`,
    ],
  }
  return base[siteType] || base.business
}

function buildNonTriggers(siteType) {
  const map = {
    ecommerce: [
      'General product research not specific to this shop',
      'Competitor pricing comparisons',
    ],
    service: [
      'DIY repair guides or tutorials',
      'Services not listed on the site',
    ],
    'developer-docs': [
      'General programming questions unrelated to this tool',
      'Other platforms or competing tools',
    ],
    business: [
      'General industry information',
      'Questions about other businesses',
    ],
  }
  return map[siteType] || ['Topics not covered by this site']
}

function getLargestPage(info) {
  if (!info.pages || info.pages.length === 0) return info.tokenCount || 0
  return Math.max(...info.pages.map(p => p.tokenCount || 0))
}
